id: P000158
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །ཆོས་རྗེ་མི་ཕམ་མགོན་པོས་དྲི་བ་སྔ་ཕྱི་ཐ་དད་མཛད་པའི་དྲིས་ལན་ཐོར་བུའི་སྐོར་རྣམས་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། མཁས་གྲུབ་ཆེན་པོ་རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - yigchung
  id: TSD-TSE-11
web_metadata:
  title:
    en: A Collection of Answers to Miscellaneous Questions of the Sublime Mipham Gonpo
    bo: ཆོས་རྗེ་མི་ཕམ་མགོན་པོས་དྲི་བ་སྔ་ཕྱི་ཐ་དད་མཛད་པའི་དྲིས་ལན་ཐོར་བུའི་སྐོར་རྣམས་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ་བཞུགས་སོ།།
  collection:
    en: Tsele Natsok Rangdrol Series–  Book 11
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།–  དེབ། ༡༡
  author:
    en: Tsele Natsok Rangdrol
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  pusblisher:
    en: Tsadra Foundation Publishing
    bo: ཙཱ་འདྲ་ཐེབས་རྩ་ཚོགས་པ།
  sku: TSD-TSE-11
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: TSD-TSE-11.epub
  description:
    en: ''
    bo: ''
